# Setup
title: Anurag Sarkar
tagline: "Everyday blogs"
description: "I write when I feel it is important to share something"
url: https://anuragsarkar97.github.io
baseurl: ""
paginate: 7
permalink: pretty

# About/contact
author:
  name: Anurag sarkar
  url: https://github.com/anuragsarkar97
  email: sarkar.anurag@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
